<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Persisted pólizas (D3).
 *
 * The póliza model splits into two entries per income invoice:
 *   provision — accrual, on invoice issue: Debe 105.01.# / Haber 4xx + IVA
 *   cobro     — cash, on payment:          Debe 102.01  / Haber 105.01.#
 *
 * These happen at DIFFERENT times and are generated by different buttons, so they
 * must be stored, not recomputed. Each póliza has balanced lines (Debe = Haber),
 * and each line can carry the CFDI UUID for the contabilidad electrónica XML.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('polizas', function (Blueprint $table) {
            $table->id();
            $table->foreignId('client_id')->constrained()->cascadeOnDelete();
            $table->foreignId('period_id')->nullable()->constrained()->nullOnDelete();

            // The invoice this póliza books. Provisión and cobro for the same
            // invoice are two rows sharing invoice_id, distinguished by tipo.
            $table->foreignId('invoice_id')->nullable()->constrained()->nullOnDelete();

            $table->enum('tipo', ['provision', 'cobro', 'egreso', 'pago']);
            $table->string('num_iden')->nullable();     // NumUnIdenPol for SAT
            $table->date('fecha');
            $table->string('concepto');

            // How the cobro's payment date was established (D4): manual | complemento | estado_cuenta
            $table->string('origen_pago')->nullable();
            // Optional links to the payment source (nullable — depends on origen).
            $table->foreignId('bank_movement_id')->nullable();
            $table->string('payment_uuid')->nullable(); // complemento de pago UUID

            $table->decimal('total_cargo', 18, 2)->default(0);
            $table->decimal('total_abono', 18, 2)->default(0);
            $table->boolean('cuadra')->default(false);

            $table->timestamps();

            $table->index(['client_id', 'period_id', 'tipo']);
            $table->index(['invoice_id', 'tipo']);
        });

        Schema::create('poliza_lines', function (Blueprint $table) {
            $table->id();
            $table->foreignId('poliza_id')->constrained()->cascadeOnDelete();
            $table->foreignId('account_id')->nullable()->constrained('accounts')->nullOnDelete();

            $table->string('numero_cuenta');   // snapshot, in case the account changes later
            $table->string('nombre_cuenta')->nullable();
            $table->string('concepto')->nullable();
            $table->string('uuid')->nullable(); // CFDI UUID backing this line (CompNal)

            $table->decimal('cargo', 18, 2)->default(0);
            $table->decimal('abono', 18, 2)->default(0);

            $table->timestamps();

            $table->index('poliza_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('poliza_lines');
        Schema::dropIfExists('polizas');
    }
};
