<?php

namespace App\Mail;

use App\Models\Client;
use App\Models\Period;
use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Attachment;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

/**
 * Emails the generated Expediente Fiscal (period summary) PDF to the client.
 * The PDF is generated by ActivityEmailService and passed as raw bytes.
 */
class ExpedienteFiscal extends Mailable
{
    use Queueable, SerializesModels;

    public function __construct(
        public Client $client,
        public Period $period,
        public string $pdfBytes,
        public string $pdfName,
    ) {}

    public function envelope(): Envelope
    {
        return new Envelope(
            subject: "Expediente Fiscal — {$this->period->label}",
        );
    }

    public function content(): Content
    {
        return new Content(
            view: 'emails.expediente_fiscal',
        );
    }

    public function attachments(): array
    {
        return [
            Attachment::fromData(fn () => $this->pdfBytes, $this->pdfName)
                ->withMime('application/pdf'),
        ];
    }
}
